### ISSUE TITLE
rails g fails - 0.3.1

### ISSUE THREAD

**Issue by wanchic** [clemens/delocalize#66]
When pulling up help with `$rails g` using delocalize-0.3.1, fails.
Using:
- ruby 2.0.0-p247
- rails 4.0.0

```
/home/user/.rvm/gems/ruby-2.0.0-p247/gems/delocalize-0.3.1/lib/delocalize/rails_ext/action_view.rb:6:in `<top (required)>': uninitialized constant ActionView::Helpers::InstanceTag (NameError)
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/delocalize-0.3.1/lib/delocalize/railtie.rb:9:in `block (2 levels) in <class:Railtie>'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/delocalize-0.3.1/lib/delocalize/railtie.rb:8:in `block in <class:Railtie>'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
	from /home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/user/Projects/the_quiz_project/question_what/config/environment.rb:5:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:189:in `require'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:189:in `require_environment!'
	from /home/user/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:45:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by clemens** [comment]
The 1.0.0 release doesn't override Rails' core classes (apart from potentially injecting a module with new methods that include a `delocalize` prefix to avoid collisions into `ActionController::Parameters`) – so this issue is gone.
